# Generated by Django 5.1.3 on 2025-01-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_alter_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
    ]

